name: Client Build Stardust

on: 
  push:
    branches: [feat/stardust]
    paths:
      - "src/**"
      - ".github/workflows/build-stardust.yml"
  pull_request:
    branches: [feat/stardust]
    paths:
      - "src/**"
      - ".github/workflows/build-stardust.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Client Build
        run: |
          npm install
          npm run build